# Bình Chánh

```{r}
library(readxl)
library(EpiEstim)
library(ggplot2)
library(dplyr)
library(janitor)
library(tidyr)
library(knitr)
library(lubridate)

df1 <- read_xlsx("C:/Users/Admin/Desktop/measles/data/data.xlsx", sheet = "data")
df1 <- as.data.frame(df1)
```



```{r}
df1 <- df1 %>% clean_names()

df <- df1 %>% rename(dates = ngay_khoi_phat,
                    ngaysinh = ngay_sinh,
                    ngaynv = ngay_nhap_vien_kham,
                    tiemchung = tinh_trang_tiem_chung,
                    gioi = gioi_tinh)

sum(is.na(df$dates))
```


```{r}
# Lấy ngày nhập viện thay cho ngày khởi phát của các ca missing
df$dates[is.na(df$dates)] <- df$ngaynv[is.na(df$dates)]
sum(is.na(df$dates))
```

```{r}
df$cd <- ifelse(df$phan_loai_chan_doan == "Loại trừ sởi", NA, df$phan_loai_chan_doan)
head(df)
df <- df[,c("dates", "ngaysinh", "tiemchung", "cd", "tinh_th","qh_th","px_th")]
df_bc <- df %>% filter (qh_th =="Bình Chánh")

# Loại những ca Sởi loại trừ
df_bc <- na.omit(df_bc)

df_convert_bc <- df %>% group_by(dates) %>% 
  summarise(I = n())

df_complete_bc <- df_convert_bc %>%
    complete(dates = seq(min(dates), max(dates), by = "day")) %>%
    replace_na(list(I = 0))

df_complete_bc$dates <- as.Date(df_complete_bc$dates)
```



```{r}
mod_raw_bc <- estimate_R(
  incid = df_complete_bc, # Dữ liệu từ 04/03/2024 - end
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, 
      std_si = 3.25
    )
  )
)
```


```{r}
df_rt_raw_bc <- mod_raw_bc$R
df_rt_raw_bc$dates <- mod_raw_bc$dates[df_rt_raw_bc$t_end]
df_rt_raw_bc$q1_rt <- df_rt_raw_bc$`Quantile.0.025(R)`
df_rt_raw_bc$q3_rt <- df_rt_raw_bc$`Quantile.0.975(R)`
df_rt_raw_bc$rt <- df_rt_raw_bc$`Mean(R)`
```

```{r}
library(patchwork)

p_hist_raw_bc <- ggplot(df_complete_bc, aes(x = dates, y = I)) +
    geom_histogram(stat = "identity", binwidth = 1, width = 1, fill = "lightgrey", color = "black") +
    labs(x = "Day", y = "Incidence") +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) + 
    scale_x_date(date_labels = "%b %d", date_breaks = "1 week", limits = c(ymd("2024-03-04"), ymd("2024-09-14")))

p_raw_bc <- ggplot(df_rt_raw_bc, aes(x = dates)) +
  geom_ribbon(aes(ymin = q1_rt, ymax = q3_rt), fill = "lightcoral", alpha = 0.3) + 
  geom_line(aes(y = rt), color = "darkorange") +
  geom_hline(yintercept = 1, linetype = "dashed", color = "black") + 
  labs(x = "Day", y = "Rt", title = "04/03/2024 - 14/09/2024") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week", limits = c(ymd("2024-03-04"), ymd("2024-09-14"))) +
  scale_y_continuous(limits = c(0, 20))

p_hist_raw_bc/p_raw_bc
```

```{r}
# Lọc dữ liệu từ 27/05/2024 - end
df_filter_bc <- filter(df_complete_bc, dates >= "2024-05-27")
```


```{r}
# SW = 14
t_start <- seq(2, nrow(df_filter_bc)-13)
t_end <- t_start + 13

mod_2w_bc <- estimate_R(
  incid = df_filter_bc, 
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, 
      std_si = 3.25,
      t_start = t_start,
      t_end = t_end
    )
  )
)

# Lấy dữ liệu ra để vẽ Rt
df_rt_2w_bc <- mod_2w_bc$R
df_rt_2w_bc$dates <- mod_2w_bc$dates[df_rt_2w_bc$t_end]
df_rt_2w_bc$q1_rt <- df_rt_2w_bc$`Quantile.0.025(R)`
df_rt_2w_bc$q3_rt <- df_rt_2w_bc$`Quantile.0.975(R)`
df_rt_2w_bc$rt <- df_rt_2w_bc$`Mean(R)`
```


```{r}
p_hist_bc <- ggplot(df_filter_bc, aes(x = dates, y = I)) +
    geom_histogram(stat = "identity", binwidth = 1, width = 1, fill = "lightgrey", color = "black") +
    labs(x = "Day", y = "Incidence") +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) + 
    scale_x_date(date_labels = "%b %d", date_breaks = "1 week", limits = c(ymd("2024-05-27"), ymd("2024-09-14")))

# Biểu đồ cho 2 tuần
p_2w_bc <- ggplot(df_rt_2w_bc, aes(x = dates)) +
  geom_ribbon(aes(ymin = q1_rt, ymax = q3_rt), fill = "lightcoral", alpha = 0.3) + 
  geom_line(aes(y = rt), color = "darkorange") +
  geom_hline(yintercept = 1, linetype = "dashed", color = "black") + 
  labs(x = "Day", y = "Rt", title = "Rt Sởi Huyện Bình Chánh") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) + 
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week", limits = c(ymd("2024-05-27"), ymd("2024-09-14"))) +
  scale_y_continuous(limits = c(0, 6))+
   annotate("text", x =ymd("2024-08-31"), y = 5, 
           label = "Chiến dịch tiêm sởi", 
           color = "red")+
     annotate("text", x =ymd("2024-08-31"), y = 4, 
           label = "31/8/2024", 
           color = "red")+
   annotate("segment", x = ymd("2024-08-31"), 
            xend = ymd("2024-08-31"), y = 3.5, yend = 2, 
           arrow = arrow(
             type = "closed", length = unit(0.2, "cm")), color = "blue")

p_hist_bc / p_2w_bc
```

```{r}
library(knitr)
kable(df_rt_2w_bc[,c("dates", "rt")])
```